// ⚠️ AUTO-GENERATED by prisma/seed.ts — DO NOT EDIT MANUALLY
// 此占位符会在构建时被 seed 脚本覆盖为真实的 AUTH_SECRET。
// This placeholder is overwritten at build time by the seed script.
export const AUTH_SECRET: string = "";
