import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import crypto from "crypto";
import fs from "fs";
import path from "path";

const prisma = new PrismaClient();

function generateSlug(length = 8): string {
  const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
  const bytes = crypto.randomBytes(length);
  let slug = "";
  for (let i = 0; i < length; i++) {
    slug += chars[bytes[i] % chars.length];
  }
  return slug;
}

function generatePassword(length = 8): string {
  const upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  const lower = "abcdefghijklmnopqrstuvwxyz";
  const digits = "0123456789";
  const all = upper + lower + digits;
  const bytes = crypto.randomBytes(length);
  let pwd = "";
  for (let i = 0; i < length; i++) {
    pwd += all[bytes[i] % all.length];
  }
  return (
    upper[bytes[0] % upper.length] +
    lower[bytes[1] % lower.length] +
    digits[bytes[2] % digits.length] +
    pwd.slice(3)
  );
}

/**
 * 确保 AUTH_SECRET 存在（跨 Vercel 部署持久化版本）：
 * 1. process.env.AUTH_SECRET 已有 → 直接用（Vercel 环境变量）
 * 2. 数据库 AppSetting 表有存储 → 从中读取，注入 process.env
 * 3. 都没有 → 生成新 secret → 存入 DB → 注入 process.env
 *
 * Vercel 部署建议：首次部署后，去 Vercel Dashboard → Environment Variables
 * 添加 AUTH_SECRET，这样 seed 和 runtime 都能直接读到，不再依赖 DB 查询。
 */
function ensureAuthSecret(): void {
  const envPath = path.resolve(process.cwd(), ".env");

  // ---- 第 1 优先：环境变量（Vercel Dashboard 设置或 .env 文件）----
  if (process.env.AUTH_SECRET) {
    console.log("🔑 AUTH_SECRET: 使用已有环境变量");
    return;
  }

  // ---- 异步部分用同步写文件兜底，真实流程在 main 中执行 ----
  // 生成新 secret 并写入 .env（本地开发持久化）
  const secret = crypto.randomBytes(32).toString("hex");

  let envContent = "";
  try {
    envContent = fs.readFileSync(envPath, "utf-8");
  } catch {
    // .env 不存在
  }

  if (envContent.includes("AUTH_SECRET=")) {
    envContent = envContent.replace(
      /^AUTH_SECRET=.*$/m,
      `AUTH_SECRET="${secret}"`
    );
    fs.writeFileSync(envPath, envContent, "utf-8");
  } else {
    const line = `\n# Auto-generated AUTH_SECRET (do not modify)\nAUTH_SECRET="${secret}"\n`;
    fs.appendFileSync(envPath, line, "utf-8");
  }

  process.env.AUTH_SECRET = secret;
  console.log("🔑 AUTH_SECRET: 已生成（.env + 当前进程）");
  console.log(`   ${secret}`);
}

/**
 * 从数据库 AppSetting 表读取 AUTH_SECRET 并注入进程环境
 * 在 process.env.AUTH_SECRET 未设置时调用
 */
async function loadAuthSecretFromDB(): Promise<void> {
  if (process.env.AUTH_SECRET) return;

  try {
    const setting = await prisma.appSetting.findUnique({ where: { key: "AUTH_SECRET" } });
    if (setting) {
      process.env.AUTH_SECRET = setting.value;
      console.log("🔑 AUTH_SECRET: 从数据库读取（跨部署持久化）");
      return;
    }
  } catch {
    // 表还不存在或 DB 不通，忽略
  }

  // DB 也没有 → 用 seed 刚生成的
  if (!process.env.AUTH_SECRET) {
    const secret = crypto.randomBytes(32).toString("hex");
    process.env.AUTH_SECRET = secret;
    console.log("🔑 AUTH_SECRET: 新生成（兜底）");
    console.log(`   ${secret}`);
  }
}

/**
 * 数据库前置检查：
 * - DATABASE_URL 环境变量是否已配置
 * - 数据库是否可连通
 * 任意一项不通过 → 直接报错退出
 */
async function checkDatabase(): Promise<void> {
  if (!process.env.DATABASE_URL) {
    console.error("❌ 未找到 DATABASE_URL 环境变量");
    console.error("   请在 .env 或部署平台环境变量中配置数据库连接地址");
    process.exit(1);
  }

  console.log("🔍 检测数据库连接...");

  try {
    await prisma.$queryRawUnsafe("SELECT 1");
    console.log("✅ 数据库连接正常");
  } catch (error) {
    console.error("❌ 数据库连接失败，请检查 DATABASE_URL 是否正确");
    if (error instanceof Error) {
      console.error(`   ${error.message}`);
    }
    process.exit(1);
  }
}

/** 确保 AUTH_SECRET 已保存到数据库（幂等） */
async function saveAuthSecretToDB(secret: string): Promise<void> {
  try {
    const existing = await prisma.appSetting.findUnique({ where: { key: "AUTH_SECRET" } });
    if (!existing) {
      await prisma.appSetting.create({ data: { key: "AUTH_SECRET", value: secret } });
      console.log("🔑 AUTH_SECRET: 已写入数据库 AppSetting 表");
    }
  } catch {
    // AppSetting 表尚未被 db push 创建，等 push 后重试
    console.warn("⚠ AppSetting 表尚未就绪，将在 db push 后生效");
  }
}

/** 将 AUTH_SECRET 写入 src/lib/auth-secret.ts，供 NextAuth 在构建时注入 */
function writeAuthSecretFile(secret: string): void {
  const filePath = path.resolve(process.cwd(), "src/lib/auth-secret.ts");
  const content = [
    "// ⚠️ AUTO-GENERATED by prisma/seed.ts — DO NOT EDIT MANUALLY",
    `export const AUTH_SECRET: string = ${JSON.stringify(secret)};`,
    "",
  ].join("\n");
  fs.writeFileSync(filePath, content, "utf-8");
  console.log("📄 AUTH_SECRET: 已写入 src/lib/auth-secret.ts（构建时注入）");
}

async function main() {
  // ---- 最早执行：数据库连接检测 ----
  await checkDatabase();

  // ---- AUTH_SECRET：DB 优先，.env 兜底 ----
  await loadAuthSecretFromDB();

  // 只有 env 和 DB 都没有时才生成新的（写入 .env + 当前进程）
  const hadSecretBefore = !!process.env.AUTH_SECRET;
  ensureAuthSecret();

  // 新生成的 secret 需要写入 DB 以跨部署持久化
  if (!hadSecretBefore && process.env.AUTH_SECRET) {
    await saveAuthSecretToDB(process.env.AUTH_SECRET);
    console.log("");
    console.log("┌─────────────────────────────────────────────────────────────┐");
    console.log("│  ⚠  Vercel 部署建议                                        │");
    console.log("│                                                            │");
    console.log("│  如需更强保障，请将此值添加到 Vercel Environment Variables：   │");
    console.log(`│  AUTH_SECRET = ${process.env.AUTH_SECRET.substring(0, 12)}...  │`);
    console.log("│  （已存 DB + 本地文件，不设置也能正常工作）                       │");
    console.log("└─────────────────────────────────────────────────────────────┘");
    console.log("");
  }

  // 🔑 关键：将 secret 写入 src/lib/auth-secret.ts
  // 构建时（next build）会将该文件编译进产物，运行时无需环境变量
  if (process.env.AUTH_SECRET) {
    writeAuthSecretFile(process.env.AUTH_SECRET);
  }

  const ADMIN_EMAIL = process.env.ADMIN_EMAIL || "admin@example.com";
  const fromEnv = !!process.env.ADMIN_PASSWORD;
  const ADMIN_PASSWORD = fromEnv
    ? process.env.ADMIN_PASSWORD!
    : generatePassword();

  console.log("🌱 开始初始化数据库...");

  // 检查是否已存在 admin 用户
  const existingAdmin = await prisma.user.findFirst({
    where: {
      OR: [
        { username: "admin" },
        { email: ADMIN_EMAIL },
      ],
    },
  });

  if (existingAdmin) {
    console.log("⏭ 管理员账号已存在，跳过创建...");

    // 已有管理员，确保存在默认分类 + 补齐 slug
    const existingCategory = await prisma.category.findFirst();

    if (!existingCategory) {
      await prisma.category.create({
        data: {
          name: "默认分类",
          slug: generateSlug(),
          sortOrder: 0,
        },
      });
      console.log("✅ 默认分类已创建");
    } else if (!existingCategory.slug) {
      await prisma.category.update({
        where: { id: existingCategory.id },
        data: { slug: generateSlug() },
      });
      console.log("✅ 默认分类 slug 已补齐");
    }

    return;
  }

  // 创建管理员用户
  const hashedPassword = await bcrypt.hash(ADMIN_PASSWORD, 10);
  await prisma.user.create({
    data: {
      username: "admin",
      name: "admin",
      email: ADMIN_EMAIL,
      password: hashedPassword,
    },
  });

  console.log("✅ 管理员账号已创建");
  console.log("   用户名: admin");
  console.log("   密码: " + (fromEnv ? "（来自环境变量 ADMIN_PASSWORD）" : ADMIN_PASSWORD));
  console.log("   邮箱: " + ADMIN_EMAIL);

  if (!fromEnv) {
    console.log("   ⚠ 请妥善保管以上密码，本次部署后不再显示");
  }

  // 创建默认分类
  await prisma.category.create({
    data: {
      name: "默认分类",
      slug: generateSlug(),
      sortOrder: 0,
    },
  });

  console.log("✅ 默认分类已创建");
  console.log("🎉 数据库初始化完成!");
}

main()
  .catch((e) => {
    console.error("❌ 初始化失败:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
